import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'

import styles from './common-layout.module.scss'
import { Header } from './header/header'
import { Footer } from './footer/footer'

export const CommonLayout = ({ children }) =>
{
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
      </Head>

      <main className={styles.lotteryAppWrapper}>
        <section className={styles.headerSection}>
          <Header />
        </section>

        <section className={styles.contentSection}>
          {children}
        </section>

        <section className={styles.footerSection}>
          <Footer />
        </section>
      </main>
    </>
  )
}